### ISSUE TITLE
Erreur lors du link

### ISSUE THREAD

**Issue by antoineok** [TrixCMS-V-2/trixcore-for-minecraft#1]
Lors ce que j'ajoute un serveur, la commande trixcore marche, mais me met une erreur lors de l'ajout du serveur coté site
`java.lang.AbstractMethodError: eu.trixcms.trixcore.common.request.RequestHandler.handle(Ljava/lang/String;Lorg/eclipse/jetty/server/Request;Linfo/journeymap/shaded/org/javax/servlet/http/HttpServletRequest;Linfo/journeymap/shaded/org/javax/servlet/http/HttpServletResponse;)V`

**Comment by iambluedev1** [comment]
hum est-ce que tu pourrais envoyer la stacktrace entière ?

**Comment by antoineok** [comment]
`> [13:40:51] [qtp239795278-7984/WARN]: 2020-06-30 13:40:51.220:WARN:oejs.HttpChannel:qtp239795278-7984: /req
java.lang.AbstractMethodError: eu.trixcms.trixcore.common.request.RequestHandler.handle(Ljava/lang/String;Lorg/eclipse/jetty/server/Request;Linfo/journeymap/shaded/org/javax/servlet/http/HttpServletRequest;Linfo/journeymap/shaded/org/javax/servlet/http/HttpServletResponse;)V
at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:132)
at org.eclipse.jetty.server.Server.handle(Server.java:564)
at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:317)
at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:251)
at org.eclipse.jetty.io.AbstractConnection$ReadCallback.succeeded(AbstractConnection.java:279)
at org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:110)
at org.eclipse.jetty.io.ChannelEndPoint$2.run(ChannelEndPoint.java:124)
at org.eclipse.jetty.util.thread.Invocable.invokePreferred(Invocable.java:128)
at org.eclipse.jetty.util.thread.Invocable$InvocableExecutor.invoke(Invocable.java:222)
at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.doProduce(EatWhatYouKill.java:294)
at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.produce(EatWhatYouKill.java:126)
at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:672)
at org.eclipse.jetty.util.thread.QueuedThreadPool$2.run(QueuedThreadPool.java:590)
at java.lang.Thread.run(Thread.java:748)`

**Comment by antoineok** [comment]
voila la stacktrace

**Comment by iambluedev1** [comment]
merci c'est fix c'était une incompatibilité avec le mod journeymap sur mohist.
cf: 
- [ca8074ecef0f133238f8f6ca0cdaaef516de53e7](https://github.com/TrixCMS-V-2/trixcore-for-minecraft/commit/ca8074ecef0f133238f8f6ca0cdaaef516de53e7)
- [df61aad52eb49103c9c816439f5e0029607ac9e0](https://github.com/TrixCMS-V-2/trixcore-minecraft-bukkit/commit/df61aad52eb49103c9c816439f5e0029607ac9e0)
